
# COMMAND for 2-bit (4-level) quantization
# python entrance.py ptq --qlvl_w 4 --qlvl_a 4 --round 1 --config ../config/lits_ptq.yaml  --pretrain ../pretrain/lits/round1/mid/state_4000.pkl --data_dir ../data/seg/LiTS/train_crop_npy_256 --split_dir ../data/seg/LiTS/split
# 

# general
task: lits


# data
data_dir:
split_dir:
patch_size: 128,128,64
batch_size: 1
test_batch_size: 1
random_noise_p:
num_workers: 4

# train

# model
model: UResQ
nMod: 1
nClass: 3
init_stride: 2,2,1
depth: 1,1,1,1,1,1,1,1,1
width: 32,64,128,256,512,256,128,64,32
dilation: 1,1,1,1,1,1,1,1,1
nla: relu
drop_rate: 0.5
ds: simple
hetero_dim: true
blk: mid

# ptq config
qconv: effq
q_first: 256,-1 
q_last: 256,-1 
lwq_dataid: 0
lwq_batchsz: 1
lwq_patchsz: 192,128,64 

